language: node_js
node_js:
  "node"

os:
  - windows

before_install:
  - mkdir nuget
  - curl -o nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget/nuget.exe install openssl-vc141-static-x86_64 -Version 1.0.2 -OutputDirectory nuget

install:
  - npm install

before_script:
  - cp win/libeay32.dll build/Release

script:
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
